version: "3"
services:
  data-collector:
    build: ../data-collector
    ports:
      - "8080:8080"
    environment:
      DATA_COLLECTOR_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  social-rating-calculator:
    build: ../social-rating-calculator
    environment:
      CALCULATOR_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CALCULATOR_REDIS_HOST: redis
      CALCULATOR_REDIS_PORT: 6379
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"